### ISSUE TITLE
Исользование синонимов типов

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/ben#10]
Такие синонимы иногда не вносят ясности, а только сбивают с толку. 
```
type MessageId = Integer
type UpdateId = Integer
type Offset = Integer
```
Не всегда очевидно, что это один и тоже тип `Integer`. Лучше использовать `newtype` в таком случае для типобезопасности, и дерайвить все необходимые инстансы:

`newtype MessageId = MessageId Integer deriving newtype (Eq, Show ...)`

**Comment by JekaGrib** [comment]
Здравствуй. Поняла, это я исправлю. Сейчас сильно изменила структуру проекта по ишью 4 (повторяющийся код). Думаю исправлять остальное только после мерджа по тем изменениям (по ишью 4). Или так неправильно?

**Comment by roman-bodavskiy** [comment]
Да конечно, либо сделать мердж, либо делать изменения в той же ветке, чтобы избегать ненужных ребейзов

**Comment by JekaGrib** [comment]
Мерж делать после того, как ты посмотришь?

**Comment by JekaGrib** [comment]
Я просто сильно не уверена, что правильно исправила.

**Comment by roman-bodavskiy** [comment]
Вообще мерж делается когда есть аппрувы. Мне сложно такие большие изменения ревьюить, так как я вообще еще не знаю проект. Пусть Сергей тоже посмотрит

**Comment by roman-bodavskiy** [comment]
Но общий смысл вроде верный. Вынести общие повторяющиеся куски логики вк и телеграм отдельно

**Comment by JekaGrib** [comment]
А я могу как-то Сергея попросить посмотреть?

**Comment by JekaGrib** [comment]
Попросила Svetlana Dulceva передать Сергею

**Comment by JekaGrib** [comment]
Всё, с Сергеем договорились. Исправления все буду делать в том пул реквесте

**Comment by JekaGrib** [comment]
А потом он всё проверит

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/ben/pull/9/commits/b02e0ab5d5fe53fef132294612bd83d72f4808e6 Исправила для чисел. Нужно ли для текста? Такие: 

`type Url = T.Text

type ServerUrl = T.Text

type DocUrl = T.Text

type PicUrl = T.Text`

**Comment by roman-bodavskiy** [comment]
> [b02e0ab](https://github.com/JekaGrib/ben/commit/b02e0ab5d5fe53fef132294612bd83d72f4808e6) Исправила для чисел. Нужно ли для текста? Такие:
> 
> `type Url = T.Text
> 
> type ServerUrl = T.Text
> 
> type DocUrl = T.Text
> 
> type PicUrl = T.Text`

Ну как минимум один `Url` сделать можно. Все 4 плодить необязательно

**Comment by JekaGrib** [comment]
#10 https://github.com/JekaGrib/ben/pull/9/commits/d8035152f07a6f8c3bf23092128b50ed244e489b
