### ISSUE TITLE
MonadStateTwo

### ISSUE THREAD

**Issue by roman-bodavskiy** [JekaGrib/ben#11]
Можешь объяснить, зачем нужен такой сложный класс

```
class (MonadState (s1, s2) m) => MonadStateTwo s1 s2 m | m -> s1 s2 where
  get1 :: m s1
  get2 :: m s2
  put1 :: s1 -> m ()
  put2 :: s2 -> m ()
  modify1 :: (s1 -> s1) -> m ()
  modify2 :: (s2 -> s2) -> m ()
```

Может будет более выразительно использовать обычный `StateT AppState:`

```
data AppState = AppState
  { tryServer :: TryServer,
    mapUserN :: MapUserN
  }
```
и `gets tryServer` вместо `get1`?
Если у класса есть только один инстанс, то его можно заменить на обычные функции с более понятными именами
`put1` и `put2` кстати вообще нигде не используются

**Comment by JekaGrib** [comment]
Спасибо за информацию. В новой версии MonadStateTwo уже нет

**Comment by roman-bodavskiy** [comment]
И все таки я не совсем понял, зачем нужен `StateT`  внутри `StateT`?
`type AppT m = StateT TryServer (StateT MapUserN m)`
Почему нельзя сделать один `StateT` а состояние собрать в один тип?
```
data AppState = AppState
  { tryServer :: TryServer,
    mapUserN :: MapUserN
  }
```
для бизнес логики, если нужно только одно внутреннее поле `mapUserN`, можно определить инстанс `MonadState MapUserN m` для `StateT AppState`:

```
chooseActionOfUpd ::
  (MonadCatch m, Attachy a,  MonadState MapUserN m) =>    -- (либо HasUserMap m)
  Handle m a ->
  ValidUpdate a ->
  m ()
```

**Comment by JekaGrib** [comment]
Я застряла. Пытаюсь сделать инстанс для StateT AppState:
`````
instance (Monad m) => MonadState MapUserN (StateT AppState m) where
  get = gets mapUserN
  put map = modify (\AppState server _ -> AppState server map)

data AppState = AppState
  { tryServer :: TryServer,
    mapUserN :: MapUserN
  }  
```

Выдает конфликт с библиотекой Control.Monad.State.Class:

```
Functional dependencies conflict between instance declarations:
      instance Monad m => MonadState MapUserN (StateT AppState m)
        -- Defined at src/Vk/AppT.hs:12:10
      instance [safe] Monad m => MonadState s (StateT s m)
        -- Defined in ‘Control.Monad.State.Class’
   |
12 | instance (Monad m) => MonadState MapUserN (StateT AppState m) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

P.S. Для телеграмма всё собралось

**Comment by JekaGrib** [comment]
А ещё, если делать:
```
chooseActionOfUpd ::
  (MonadCatch m, Attachy a,  MonadState MapUserN m) =>    -- (либо HasUserMap m)
  Handle m a ->
  ValidUpdate a ->
  m ()
```
То , получается, нужно передавать на запуске Handle (StateT AppState IO) , а у меня Handle IO (приходится лифтить хэндл)
Может лучше оставить IO отдельным слоем, а на него накручивать:

```
chooseActionOfUpd ::
  (MonadTrans t, MonadCatch m, Attachy a,  MonadState MapUserN (t m)) =>   
  Handle m a ->
  ValidUpdate a ->
  t m ()
```

**Comment by roman-bodavskiy** [comment]
> 
> Выдает конфликт с библиотекой Control.Monad.State.Class:
> 

Согласен, можно конечно сделать какую-нибудь обертку, но мне такой вариант не очень нравится:
```
newtype MapUserStateT m a = MapUserStateT {getMapUserState :: StateT AppState m a} 
  deriving newtype (Functor, Applicative, Monad)
```

**Comment by roman-bodavskiy** [comment]
Мне больше нравится другой вариант, добавить класс

```
class HasUserMap m where
  getUserMap :: m MapUserN
  setUserMap :: MapUserN -> m ()
  modifyUserMap :: (MapUserN -> MapUserN) -> m ()
```

и два инстанса для него, один для Вк, другой для телеграм

```
instance HasUserMap (StateT MapUserN m) where
  getUserMap = error "TODO"
  setUserMap = error "TODO"
  modifyUserMap = error "TODO"

instance  HasUserMap (StateT AppState m) where
  getUserMap = error "TODO"
  setUserMap = error "TODO"
  modifyUserMap = error "TODO"
```

Можно добавить функции для удобства доступа к полям, если надо

```
modifyTryServer :: Monad m => (TryServer -> TryServer) -> AppT m ()
modifyTryServer f = do
  modify $ \appState ->
    appState {tryServer = f (tryServer appState)}
```

Тогда общая логика будет выглядеть так

```
chooseActionOfUpd ::
  (MonadCatch m, Attachy a, HasUserMap m) =>
  Handle m a ->
  ValidUpdate a ->
  m ()
```

Чтобы все скомпилилось прийдется еще добавить функции для лифта хендлов:

```
liftHandler1 :: App.Handle m a -> App.Handle (AppT m) a
liftHandler1 = error "TODO"
```

Этот вариант я попробовал, он точно компилится

**Comment by roman-bodavskiy** [comment]
Если это переделаешь, то вопросов к боту больше нет. Сервер еще гляну

**Comment by roman-bodavskiy** [comment]
> (MonadTrans t, MonadCatch m, Attachy a,  MonadState MapUserN (t m)) =>   
>   Handle m a ->
>   ValidUpdate a ->
>   t m ()

Выглядит сложно, мне кажется мой вариант проще. Ну прийдется лифтить хендлы, но по-моему это легко делается

**Comment by JekaGrib** [comment]
https://github.com/JekaGrib/ben/issues/11 https://github.com/JekaGrib/ben/commit/3ef21f2afefa6208a540bebcc9fa9e3831ce5b65
