### ISSUE TITLE
Поля ADT 

### ISSUE THREAD

**Issue by ghost** [JekaGrib/ben#3]
1)
https://github.com/JekaGrib/ben/blob/538d36508df7fe7d34221fc9856b00e9aa0e8351/src/Tg/Api/Response.hs#L33-L40
При создании подобных типов создаются нетотальные функции. Функция message может быть ипользована на значении UnknownUpdate и мы получим райнтайм ошибку.

2)
По проекту, а иногда и в рамках одного типа, встречается неоднородное именование полей. Одни поля именованы в snake_case, а другие в camelCase. Необходимо привести поля к однородному виду. В Haskell обычно используют camelCase.

**Comment by JekaGrib** [comment]
Подскажи, пожалуйста. Сижу все думаю. Если убрать Record Syntax, проблема решится(нетотальных функций не будет)? Или полностью типы нужно как-то переписать? 
Пример: 
 data Update = Update UpdateId Message | UnknownUpdate UpdateId

**Comment by ghost** [comment]
Можно так. Ещё можно конструкторы значений вынести в 2 отдельных типа-произведения и объединить их типом-суммой.

**Comment by JekaGrib** [comment]
Про неоднородное именование полей помню
