### ISSUE TITLE
Повторяющийся код

### ISSUE THREAD

**Issue by ghost** [JekaGrib/ben#4]
Основной целью задания было вынести общую для двух ботов логику, чтобы в последствии можно было легко подключить другие мессенджеры. На данный момент в проекте скорее 2 бота, чем один. Файлы в папках Tg и Vk содержат идентичные функции, а иногда и весь модуль повторяется. Весь повторяющийся код, а так же бизнес логику необходимо вынести отдельно и переиспользовать посредством импорта, а не копирования кода.

**Comment by roman-bodavskiy** [comment]
Мелкие фрагменты кода тоже часто повторяются, например там где идет перечисление от 1 до 5
```
            [ [KeyButton {textBtn = "1"}],
              [KeyButton {textBtn = "2"}],
              [KeyButton {textBtn = "3"}],
              [KeyButton {textBtn = "4"}],
              [KeyButton {textBtn = "5"}]
            ],
```
